# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 007127dad1d467426120dd214f42c380956bbe9a3412c30be111347c7cb714b6199ab2bb09c534988b3db395f87b938094316f14079ef03793387c2a64d74939

test:
  secret_key_base: abcab513d55d3a994395630ccdc376664f74c4bdc0d27e7cf3811b5142437b7ae3faad2f0b05e8475ab214e5f1e652e36b21c572667c0519080e2748fa5a51ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
